### ISSUE TITLE
Latex Equations in Tables

### ISSUE THREAD

**Issue by rowanc1** [curvenote/schema#24]
We are displaying inline text, and that skips the important defining nodes. For equations, they need to be treated differently if they are in a table.

https://tex.stackexchange.com/questions/76189/how-to-put-a-formula-into-a-table-cell

There are a few different options, on taking a look through I think that we could do `\(\displaystyle ... \)` if we are in a table for equations. And skip numbering etc.

Maybe we can look at the children and if there is one paragraph, display inline, otherwise just print. This should satisfy most usecases.

![image](https://user-images.githubusercontent.com/913249/134431253-cb0c75fb-8ac4-487d-b887-4bff56eef189.png)

A few examples here:
https://curvenote.com/@curvenote/examples/tables

**Comment by Yxwww** [comment]
See https://github.com/curvenote/schema/pull/25

**Comment by rowanc1** [comment]
This is closed in c01b580fe6b01437ab920a0325c77b22fc94e3ae
